apiVersion: v1
kind: Service
metadata:
  name: external-service-pihole-webadmin
  namespace: ingress-nginx
spec:
  clusterIP: None
  ports:
  - port: 8489
    targetPort: 8489
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-service-pihole-webadmin
  namespace: ingress-nginx
subsets:
  - addresses:
      - ip: 192.168.0.2
    ports:
      - port: 8489
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-ingress
  namespace: ingress-nginx
  annotations:
    # This annotation tells Nginx to redirect all requests for '/'
    # to '/admin'. The 'permanent' means 301 (SEO-friendly).
    nginx.ingress.kubernetes.io/permanent-redirect: /admin/
    # Alternative for rewrite, but for / to /admin, temporary-redirect is cleaner for simple redirection.
    # If you use rewrite-target, you often need to handle path stripping carefully.
    # For a simple redirect, `temporal-redirect` (302) or `permanent-redirect` (301) is often better.
    # nginx.ingress.kubernetes.io/rewrite-target: /admin
spec:
  ingressClassName: nginx
  rules:
  - host: pihole.home.oakhl.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-service-pihole-webadmin
            port:
              number: 8489

      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: external-service-pihole-webadmin
            port:
              number: 8489