apiVersion: v1
kind: Service
metadata:
  name: external-service-pihole-webadmin
  namespace: ingress-nginx
spec:
  clusterIP: None
  ports:
  - name: webadmin
    port: 8489
    targetPort: 8489
    protocol: TCP
  - name: metrics
    port: 9100
    targetPort: 9100
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-service-pihole-webadmin
  namespace: ingress-nginx
subsets:
  - addresses:
      - ip: 192.168.0.2
    ports:
      - name: webadmin
        port: 8489
      - name: metrics
        port: 9100
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-ingress
  namespace: ingress-nginx
  annotations:
    # --- Cert-manager annotations to request a certificate ---
    # This annotation tells cert-manager to use the specified ClusterIssuer
    # to obtain a certificate for the host(s) defined in the TLS section.
    cert-manager.io/cluster-issuer: "letsencrypt-prod-cloudflare-dns01"

    # --- Nginx Ingress annotations ---
    # Tells Nginx Ingress to use HTTPS when connecting to the backend service (Pi-hole at 192.168.0.2:8489)
    # Ensure your Pi-hole web admin is indeed listening on HTTPS on port 8489
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

    # Redirects / to /admin/ internally at the Ingress Controller level
    nginx.ingress.kubernetes.io/app-root: /admin/

    # Forces all HTTP traffic to be redirected to HTTPS for this Ingress
    # This is highly recommended for security.
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

spec:
  ingressClassName: nginx
  # --- TLS configuration for frontend HTTPS (browser to Ingress) ---
  # This block defines the host(s) for which TLS will be enabled and
  # the Kubernetes Secret where the certificate will be stored by cert-manager.
  tls:
    - hosts:
        - pihole.home.oakhl.com # The domain(s) this certificate will be valid for
      secretName: pihole-home-oakhl-com-tls # Name of the Secret cert-manager will create/manage

  rules:
  - host: pihole.home.oakhl.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-service-pihole-webadmin
            port:
              name: webadmin