apiVersion: v1
kind: Service
metadata:
  name: external-service-qbittorrent
  namespace: ingress-nginx
spec:
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-service-qbittorrent
  namespace: ingress-nginx
subsets:
  - addresses:
      - ip: 192.168.0.35
    ports:
      - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-ingress
  namespace: ingress-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-cloudflare-dns01"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - qbittorrent.home.oakhl.com
      secretName: qbittorrent-home-oakhl-com-tls
  rules:
  - host: qbittorrent.home.oakhl.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-service-qbittorrent
            port:
              number: 8080