---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  # values:
  #   controller:
  #     service:
  #       type: NodePort
  #       nodePorts:
  #         http: 30080
  #         https: 30443
  interval: 10m0s
