---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 70.4.2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    fullnameOverride:  prometheus
    grafana:
      fullnameOverride: grafana
    prometheus-node-exporter:
      fullnameOverride: node-exporter

  interval: 10m0s
