---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring
data:
  values.yaml: |
    fullnameOverride: prometheus
    prometheus:
      fullnameOverride: prometheus
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
        retention: 15d
    grafana:
      fullnameOverride: grafana
      adminPassword: admin
      sidecar:
        datasources:
    alertmanager:
      enabled: false
    prometheus-node-exporter:
      fullnameOverride: node-exporter
    kube-state-metrics:
      fullnameOverride: kube-state-metrics
    defaultRules:
      create: true
      interval: 10m0s