---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki-stack
      version: 2.10.2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    test_pod:
      enabled: true
      image: bats/bats:1.8.2

    loki:
      enabled: true

    promtail:
      enabled: true

    fluent-bit:
      enabled: false

    grafana:
      enabled: false
      sidecar:                                                                                                                           
        datasources:                                                                                                                     
          enabled: false
      
    prometheus:
      enabled: false

    filebeat:
      enabled: false
      
    logstash:
      enabled: false

  interval: 10m0s
