---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 70.4.2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    fullnameOverride: prometheus
    prometheus:
      fullnameOverride: prometheus
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
        retention: 15d

    grafana:
      fullnameOverride: grafana
      adminPassword: admin
      sidecar:
        datasources:
          alertmanager:
            enabled: false

    prometheus-node-exporter:
      fullnameOverride: node-exporter
    kube-state-metrics:
      fullnameOverride: kube-state-metrics
    alertmanager:
      enabled: false
    defaultRules:
      create: true
  interval: 10m0s
