apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    name: loki-stack
  endpoints:
    - port: http-metrics
  jobLabel: jobLabel